const PRODUCT = {
	FETCH: 'ACTION_FETCH_ALL_PRODUCTS',
	ADD: 'ACTION_ADD_ONE_PRODUCT',
	UPDATE: 'ACTION_UPDATE_ONE_PRODUCT',
	DELETE: 'ACTION_DELETE_ONE_PRODUCT'
}
const PROMO = {
	FETCH: 'ACTION_FETCH_ALL_PROMOS',
	ADD: 'ACTION_ADD_ONE_PROMO',
	UPDATE: 'ACTION_UPDATE_ONE_PROMO',
	DELETE: 'ACTION_DELETE_ONE_PROMO'
}
const CART = {
	FETCH: 'ACTION_FETCH_CART',
	ADD: 'ACTION_ADD_TO_CART',
	UPDATE: 'ACTION_UPDATE_TO_CART',
	DELETE: 'ACTION_DELETE_FROM_CART'
}

export {
	PRODUCT,
	PROMO,
	CART
};